name: Claude Interactive Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude-interactive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # No prompt = Interactive Mode - responde a @claude mentions
          claude_args: |
            --allowedTools "Read,Write,Edit,Grep,mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh issue comment:*),Bash(gh pr diff:*),Bash(git:*),Bash(pnpm test:*),Bash(pnpm type-check:*),Bash(pnpm lint:*)"
            --max-turns 50